version: '3.1'                          
services:
  elasticsearch:
    image: daocloud.io/library/elasticsearch:6.5.4
    restart: always
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
   #kibana图形化插件
  kibana:
    image:  daocloud.io/library/kibana:6.5.4
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://192.168.223.132:9200
    ports:
      - "5601:5601"
    depends_on:
      -  elasticsearch
