version: '3.9'

services:
   db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kid
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
